<Project>
  <PropertyGroup>
    <Authors>Michael Ciccotti</Authors>
    <Version>1.0.6</Version>
    <Copyright>Copyright (c) 2026 Michael Ciccotti</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
</Project>
